services:
  postgres:
    image: postgres:17-alpine
    container_name: ink_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1357
      POSTGRES_DB: printer_ink
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: ink_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=printer_ink
      - DB_USER=postgres
      - DB_PASSWORD=1357
    depends_on:
      - postgres

  frontend-client:
    build:
      context: ./frontend/client
      dockerfile: client.Dockerfile
    container_name: ink_frontend_client
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend

  frontend-admin:
    build:
      context: ./frontend/admin
      dockerfile: admin.Dockerfile
    container_name: ink_frontend_admin
    restart: always
    ports:
      - "3002:3002" # Админка будет доступна в браузере по адресу localhost:3002
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  pgdata:
