services:
  postgres:
    image: postgres:17-alpine
    container_name: ink_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: ink_backend
    restart: always
    ports:
      - "${PORT_BACKEND}:${PORT_BACKEND}"
    env_file:
      - .env
    environment:
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres

  frontend-client:
    build:
      context: ./frontend/client
      dockerfile: client.Dockerfile
      args:
        - CLIENT_URL=${CLIENT_URL}
        - PORT_BACKEND=${PORT_BACKEND}
    container_name: ink_frontend_client
    restart: always
    ports:
      - "${PORT_FRONTEND_CLIENT}:3000"
    env_file:
      - .env
    depends_on:
      - backend

  frontend-admin:
    build:
      context: ./frontend/admin
      dockerfile: admin.Dockerfile
      args:
        - CLIENT_URL=${CLIENT_URL}
        - PORT_BACKEND=${PORT_BACKEND}
    container_name: ink_frontend_admin
    restart: always
    ports:
      - "${PORT_FRONTEND_ADMIN}:3000"
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  pgdata:
